kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
rules:
- apiGroups:
  - "distributed-compute.dominodatalab.com"
  resources:
  - "rayclusters"
  verbs:
  - "*"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
  namespace: {{ .Values.env.namespace.compute }}
rules:
- apiGroups:
  - "distributed-compute.dominodatalab.com"
  resources:
  - "rayclusters"
  verbs:
  - "*"
